name: shell command
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
   run-shell-command:
     runs-on: ubuntu-latest
     steps:
       - name: echo a string
         run: echo "Hello World"
       - name: multiline script
         run: |

           echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
           echo "GITHUB_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} )" >> $GITHUB_TOKEN
        #   echo ${GITHUB_TOKEN}

         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
